//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace calledWebServices.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.londonsumatra.com/", ConfigurationName="ServiceReference1.WsRecruitmentSoap")]
    public interface WsRecruitmentSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.londonsumatra.com/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.londonsumatra.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.londonsumatra.com/GetEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetEmail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.londonsumatra.com/GetEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetEmailAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsRecruitmentSoapChannel : calledWebServices.ServiceReference1.WsRecruitmentSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsRecruitmentSoapClient : System.ServiceModel.ClientBase<calledWebServices.ServiceReference1.WsRecruitmentSoap>, calledWebServices.ServiceReference1.WsRecruitmentSoap {
        
        public WsRecruitmentSoapClient() {
        }
        
        public WsRecruitmentSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsRecruitmentSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsRecruitmentSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsRecruitmentSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataTable GetEmail() {
            return base.Channel.GetEmail();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetEmailAsync() {
            return base.Channel.GetEmailAsync();
        }
    }
}
