#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TopModelIndo")]
public partial class VideoListDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertVideoList(VideoList instance);
  partial void UpdateVideoList(VideoList instance);
  partial void DeleteVideoList(VideoList instance);
  #endregion
	
	public VideoListDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TopModelIndoConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public VideoListDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public VideoListDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public VideoListDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public VideoListDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<VideoList> VideoLists
	{
		get
		{
			return this.GetTable<VideoList>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VideoList")]
public partial class VideoList : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _VideoId;
	
	private System.Nullable<System.DateTime> _DateCreated;
	
	private string _VideoTitle;
	
	private string _VideoDescription;
	
	private string _VideoArtist;
	
	private string _VideoLogo;
	
	private string _VideoAddress;
	
	private System.Nullable<int> _VideoCounter;
	
	private string _WAP;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVideoIdChanging(string value);
    partial void OnVideoIdChanged();
    partial void OnDateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCreatedChanged();
    partial void OnVideoTitleChanging(string value);
    partial void OnVideoTitleChanged();
    partial void OnVideoDescriptionChanging(string value);
    partial void OnVideoDescriptionChanged();
    partial void OnVideoArtistChanging(string value);
    partial void OnVideoArtistChanged();
    partial void OnVideoLogoChanging(string value);
    partial void OnVideoLogoChanged();
    partial void OnVideoAddressChanging(string value);
    partial void OnVideoAddressChanged();
    partial void OnVideoCounterChanging(System.Nullable<int> value);
    partial void OnVideoCounterChanged();
    partial void OnWAPChanging(string value);
    partial void OnWAPChanged();
    #endregion
	
	public VideoList()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoId", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string VideoId
	{
		get
		{
			return this._VideoId;
		}
		set
		{
			if ((this._VideoId != value))
			{
				this.OnVideoIdChanging(value);
				this.SendPropertyChanging();
				this._VideoId = value;
				this.SendPropertyChanged("VideoId");
				this.OnVideoIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateCreated
	{
		get
		{
			return this._DateCreated;
		}
		set
		{
			if ((this._DateCreated != value))
			{
				this.OnDateCreatedChanging(value);
				this.SendPropertyChanging();
				this._DateCreated = value;
				this.SendPropertyChanged("DateCreated");
				this.OnDateCreatedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoTitle", DbType="NVarChar(50)")]
	public string VideoTitle
	{
		get
		{
			return this._VideoTitle;
		}
		set
		{
			if ((this._VideoTitle != value))
			{
				this.OnVideoTitleChanging(value);
				this.SendPropertyChanging();
				this._VideoTitle = value;
				this.SendPropertyChanged("VideoTitle");
				this.OnVideoTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoDescription", DbType="NVarChar(500)")]
	public string VideoDescription
	{
		get
		{
			return this._VideoDescription;
		}
		set
		{
			if ((this._VideoDescription != value))
			{
				this.OnVideoDescriptionChanging(value);
				this.SendPropertyChanging();
				this._VideoDescription = value;
				this.SendPropertyChanged("VideoDescription");
				this.OnVideoDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoArtist", DbType="NVarChar(50)")]
	public string VideoArtist
	{
		get
		{
			return this._VideoArtist;
		}
		set
		{
			if ((this._VideoArtist != value))
			{
				this.OnVideoArtistChanging(value);
				this.SendPropertyChanging();
				this._VideoArtist = value;
				this.SendPropertyChanged("VideoArtist");
				this.OnVideoArtistChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoLogo", DbType="NVarChar(50)")]
	public string VideoLogo
	{
		get
		{
			return this._VideoLogo;
		}
		set
		{
			if ((this._VideoLogo != value))
			{
				this.OnVideoLogoChanging(value);
				this.SendPropertyChanging();
				this._VideoLogo = value;
				this.SendPropertyChanged("VideoLogo");
				this.OnVideoLogoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoAddress", DbType="NVarChar(100)")]
	public string VideoAddress
	{
		get
		{
			return this._VideoAddress;
		}
		set
		{
			if ((this._VideoAddress != value))
			{
				this.OnVideoAddressChanging(value);
				this.SendPropertyChanging();
				this._VideoAddress = value;
				this.SendPropertyChanged("VideoAddress");
				this.OnVideoAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoCounter", DbType="Int")]
	public System.Nullable<int> VideoCounter
	{
		get
		{
			return this._VideoCounter;
		}
		set
		{
			if ((this._VideoCounter != value))
			{
				this.OnVideoCounterChanging(value);
				this.SendPropertyChanging();
				this._VideoCounter = value;
				this.SendPropertyChanged("VideoCounter");
				this.OnVideoCounterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WAP", DbType="NVarChar(3)")]
	public string WAP
	{
		get
		{
			return this._WAP;
		}
		set
		{
			if ((this._WAP != value))
			{
				this.OnWAPChanging(value);
				this.SendPropertyChanging();
				this._WAP = value;
				this.SendPropertyChanged("WAP");
				this.OnWAPChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
