#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TopModelIndo")]
public partial class WallPaperListDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertWallPaperList(WallPaperList instance);
  partial void UpdateWallPaperList(WallPaperList instance);
  partial void DeleteWallPaperList(WallPaperList instance);
  #endregion
	
	public WallPaperListDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TopModelIndoConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public WallPaperListDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public WallPaperListDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public WallPaperListDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public WallPaperListDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<WallPaperList> WallPaperLists
	{
		get
		{
			return this.GetTable<WallPaperList>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WallPaperList")]
public partial class WallPaperList : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _WallPaperId;
	
	private System.Nullable<System.DateTime> _DateCreated;
	
	private string _WallPaperTitle;
	
	private string _WallPaperDescription;
	
	private string _WallPaperArtist;
	
	private string _WallPaperLogo;
	
	private string _WallPaperAddress;
	
	private System.Nullable<int> _WallPaperCounter;
	
	private string _WAP;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWallPaperIdChanging(string value);
    partial void OnWallPaperIdChanged();
    partial void OnDateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCreatedChanged();
    partial void OnWallPaperTitleChanging(string value);
    partial void OnWallPaperTitleChanged();
    partial void OnWallPaperDescriptionChanging(string value);
    partial void OnWallPaperDescriptionChanged();
    partial void OnWallPaperArtistChanging(string value);
    partial void OnWallPaperArtistChanged();
    partial void OnWallPaperLogoChanging(string value);
    partial void OnWallPaperLogoChanged();
    partial void OnWallPaperAddressChanging(string value);
    partial void OnWallPaperAddressChanged();
    partial void OnWallPaperCounterChanging(System.Nullable<int> value);
    partial void OnWallPaperCounterChanged();
    partial void OnWAPChanging(string value);
    partial void OnWAPChanged();
    #endregion
	
	public WallPaperList()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WallPaperId", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string WallPaperId
	{
		get
		{
			return this._WallPaperId;
		}
		set
		{
			if ((this._WallPaperId != value))
			{
				this.OnWallPaperIdChanging(value);
				this.SendPropertyChanging();
				this._WallPaperId = value;
				this.SendPropertyChanged("WallPaperId");
				this.OnWallPaperIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateCreated
	{
		get
		{
			return this._DateCreated;
		}
		set
		{
			if ((this._DateCreated != value))
			{
				this.OnDateCreatedChanging(value);
				this.SendPropertyChanging();
				this._DateCreated = value;
				this.SendPropertyChanged("DateCreated");
				this.OnDateCreatedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WallPaperTitle", DbType="NVarChar(50)")]
	public string WallPaperTitle
	{
		get
		{
			return this._WallPaperTitle;
		}
		set
		{
			if ((this._WallPaperTitle != value))
			{
				this.OnWallPaperTitleChanging(value);
				this.SendPropertyChanging();
				this._WallPaperTitle = value;
				this.SendPropertyChanged("WallPaperTitle");
				this.OnWallPaperTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WallPaperDescription", DbType="NVarChar(500)")]
	public string WallPaperDescription
	{
		get
		{
			return this._WallPaperDescription;
		}
		set
		{
			if ((this._WallPaperDescription != value))
			{
				this.OnWallPaperDescriptionChanging(value);
				this.SendPropertyChanging();
				this._WallPaperDescription = value;
				this.SendPropertyChanged("WallPaperDescription");
				this.OnWallPaperDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WallPaperArtist", DbType="NVarChar(50)")]
	public string WallPaperArtist
	{
		get
		{
			return this._WallPaperArtist;
		}
		set
		{
			if ((this._WallPaperArtist != value))
			{
				this.OnWallPaperArtistChanging(value);
				this.SendPropertyChanging();
				this._WallPaperArtist = value;
				this.SendPropertyChanged("WallPaperArtist");
				this.OnWallPaperArtistChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WallPaperLogo", DbType="NVarChar(100)")]
	public string WallPaperLogo
	{
		get
		{
			return this._WallPaperLogo;
		}
		set
		{
			if ((this._WallPaperLogo != value))
			{
				this.OnWallPaperLogoChanging(value);
				this.SendPropertyChanging();
				this._WallPaperLogo = value;
				this.SendPropertyChanged("WallPaperLogo");
				this.OnWallPaperLogoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WallPaperAddress", DbType="NVarChar(100)")]
	public string WallPaperAddress
	{
		get
		{
			return this._WallPaperAddress;
		}
		set
		{
			if ((this._WallPaperAddress != value))
			{
				this.OnWallPaperAddressChanging(value);
				this.SendPropertyChanging();
				this._WallPaperAddress = value;
				this.SendPropertyChanged("WallPaperAddress");
				this.OnWallPaperAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WallPaperCounter", DbType="Int")]
	public System.Nullable<int> WallPaperCounter
	{
		get
		{
			return this._WallPaperCounter;
		}
		set
		{
			if ((this._WallPaperCounter != value))
			{
				this.OnWallPaperCounterChanging(value);
				this.SendPropertyChanging();
				this._WallPaperCounter = value;
				this.SendPropertyChanged("WallPaperCounter");
				this.OnWallPaperCounterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WAP", DbType="NVarChar(3)")]
	public string WAP
	{
		get
		{
			return this._WAP;
		}
		set
		{
			if ((this._WAP != value))
			{
				this.OnWAPChanging(value);
				this.SendPropertyChanging();
				this._WAP = value;
				this.SendPropertyChanged("WAP");
				this.OnWAPChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
