<%@ Control Language="C#" AutoEventWireup="true" CodeFile="ActiveTicketHistory.ascx.cs" Inherits="UserControl_Grid_ActiveTicketHistory" %>
<div class="table-responsive">
    <telerik:RadGrid ID="rgaActiveTicketHistory" runat="server" Skin="3b" EnableEmbeddedSkins="false"
        OnNeedDataSource="rgaActiveTicketHistory_NeedDataSource" 
        AllowSorting="true" AutoGenerateColumns="false"
        AutoGenerateDeleteColumn="false" AutoGenerateEditColumn="false" ShowFooter="false" Width="100%" GridLines="None" ClientSettings-Resizing-AllowColumnResize="true"> 
        <MasterTableView ShowHeadersWhenNoRecords="true" TableLayout="Fixed" DataKeyNames="PeriodNumber" Width="100%">
            <NoRecordsTemplate>
                <div style="padding: 8px 0 8px 5px;">No Records found.</div>
            </NoRecordsTemplate>
            <Columns>
                <telerik:GridBoundColumn DataField="PeriodNumber" HeaderStyle-Width="3%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="#" SortExpression="PeriodNumber" UniqueName="PeriodNumber" HeaderTooltip="PeriodNumber" />
                <telerik:GridBoundColumn DataField="StartID" Display="false" HeaderStyle-Width="5%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Start Time" SortExpression="StartID" UniqueName="StartID" HeaderTooltip="StartID" />
                <telerik:GridBoundColumn DataField="EndID" Display="false" HeaderStyle-Width="8%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="End Time" SortExpression="EndID" UniqueName="EndID" HeaderTooltip="EndID" />
                <telerik:GridBoundColumn DataField="ActiveStartTime" HeaderStyle-Width="5%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Start Time" SortExpression="ActiveStartTime" UniqueName="ActiveStartTime" HeaderTooltip="ActiveStartTime"/>
                <telerik:GridBoundColumn DataField="ActiveEndTime" HeaderStyle-Width="5%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="End Time" SortExpression="ActiveEndTime" UniqueName="ActiveEndTime" HeaderTooltip="ActiveEndTime"/>
                <telerik:GridBoundColumn DataField="SessionStatus" HeaderStyle-Width="5%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Status" SortExpression="SessionStatus" UniqueName="SessionStatus" HeaderTooltip="SessionStatus"/>
                <telerik:GridBoundColumn DataField="DurationSeconds" Display="false" HeaderStyle-Width="5%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="DurationSeconds" SortExpression="DurationSeconds" UniqueName="DurationSeconds" HeaderTooltip="DurationSeconds" />
                <telerik:GridBoundColumn DataField="DurationDays" Display="false" HeaderStyle-Width="5%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="DurationDays" SortExpression="DurationDays" UniqueName="DurationDays" HeaderTooltip="DurationDays" />
                <telerik:GridBoundColumn DataField="DurationHours" Display="false" HeaderStyle-Width="8%" DataType="System.DateTime" ItemStyle-HorizontalAlign="Left" HeaderText="DurationHours" SortExpression="DurationHours" UniqueName="DurationHours" HeaderTooltip="DurationHours" />
                <telerik:GridBoundColumn DataField="DurationMinutes" Display="false" HeaderStyle-Width="8%" DataType="System.DateTime" ItemStyle-HorizontalAlign="Left" HeaderText="DurationMinutes" SortExpression="DurationMinutes" UniqueName="DurationMinutes" HeaderTooltip="DurationMinutes" />
                <telerik:GridBoundColumn DataField="DurationSecondsOnly" Display="false" HeaderStyle-Width="8%" DataType="System.DateTime" ItemStyle-HorizontalAlign="Left" HeaderText="DurationSecondsOnly" SortExpression="DurationSecondsOnly" UniqueName="DurationSecondsOnly" HeaderTooltip="DurationSecondsOnly" />
                <telerik:GridBoundColumn DataField="DurationFormatted" HeaderStyle-Width="7%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Durations" SortExpression="DurationFormatted" UniqueName="DurationFormatted" HeaderTooltip="DurationFormatted" />
            </Columns>
        </MasterTableView>
    </telerik:RadGrid>
</div>
<asp:Literal ID="litDebug" runat="server" />