<%@ Control Language="C#" AutoEventWireup="true" CodeFile="ClientBackupReportResponsive.ascx.cs" Inherits="UserControl_Grid_ClientBackupReportResponsive" %>
<%@ Register TagPrefix="uc" tagName="GridExportTypeDDL" src="~/UserControl/DropDownList/GridExportType.ascx"  %>

    <div class="table-responsive">
        <telerik:RadGrid ID="rgClientBackupReport" runat="server"
            OnNeedDataSource="rgClientBackupReport_NeedDataSource" 
            OnItemDataBound="rgClientBackupReport_ItemDataBound"
            OnItemCreated="rgClientBackupReport_ItemCreated"
            OnPreRender="rgClientBackupReport_PreRender" 
            OnItemCommand="rgClientBackupReport_ItemCommand"
            Skin="3b" EnableEmbeddedSkins="false"
            AllowSorting="true" AllowPaging="true" AllowCustomPaging="true" AutoGenerateColumns="false"
            AutoGenerateDeleteColumn="false" AutoGenerateEditColumn="false" ShowFooter="false" Width="100%" GridLines="None" 
            ClientSettings-Resizing-AllowColumnResize="true">
    
            <ClientSettings EnableRowHoverStyle="true" AllowColumnsReorder="true" >
                <Selecting AllowRowSelect="true" />
                <Resizing AllowColumnResize="true" ClipCellContentOnResize="false" />
            </ClientSettings>
    
            <MasterTableView ShowHeadersWhenNoRecords="true" TableLayout="fixed" InsertItemPageIndexAction="ShowItemOnCurrentPage" 
                DataKeyNames="Id,IsFailure,BackupMonitorStatusName,StatusGridName,BackupSetId" CommandItemDisplay="Top" EditMode="EditForms" Width="100%">
                 
                <PagerStyle AlwaysVisible="true" Mode="NextPrevAndNumeric" PageSizes="10,25,50,100,250" PageSizeControlType="RadComboBox" Position="Bottom" />
                <NoRecordsTemplate>
                    <div style="padding: 8px 0 8px 5px;">No Records found.</div>
                </NoRecordsTemplate>
                <CommandItemTemplate>
                    <div style="margin:5px 5px;">
                        <uc:GridExportTypeDDL ID="ucGridExportType" runat="server" />&nbsp;
                        <asp:LinkButton ID="btnExport" runat="server" OnClick="btnExport_Click" style="padding-right:10px;"><i class="gi gi-circle_plus" title="Add"></i> Export</asp:LinkButton>
                        <asp:LinkButton ID="lbRefresh" runat="server" CommandName="RefreshGrid" CssClass="pull-right"><i class="gi gi-refresh" title="Refresh"></i>  Refresh</asp:LinkButton>
                    </div>
                </CommandItemTemplate> 
                                
                <Columns>
                    <telerik:GridBoundColumn UniqueName="Date" DataField="Date" SortExpression="Date" HeaderText="Monitor Date" HeaderTooltip="Monitor Date" DataFormatString="{0:MM/dd/yy}" HeaderStyle-HorizontalAlign="Center" ItemStyle-VerticalAlign="Top" HeaderStyle-Width="5%"/>
                    <telerik:GridBoundColumn UniqueName="ClientCompany" DataField="ClientCompany" SortExpression="ClientCompany" HeaderText="Client" HeaderTooltip="Client Name" HeaderStyle-HorizontalAlign="Center" ItemStyle-VerticalAlign="Top" HeaderStyle-Width="15%"/>
                    <telerik:GridBoundColumn UniqueName="Server" DataField="Server" SortExpression="Server" HeaderText="Protected Machine" HeaderTooltip="Protected Machine" HeaderStyle-HorizontalAlign="Center" ItemStyle-VerticalAlign="Top" HeaderStyle-Width="15%"/>
                    <telerik:GridBoundColumn UniqueName="BackupServer" DataField="BackupServer" SortExpression="BackupServer" HeaderText="BU Server" HeaderTooltip="Backup Server" HeaderStyle-HorizontalAlign="Center" ItemStyle-VerticalAlign="Top" HeaderStyle-Width="10%"/>
                    <telerik:GridBoundColumn UniqueName="BackupSetName" DataField="BackupSetName" SortExpression="BackupSetName" HeaderText="BU Set Name" HeaderTooltip="Backup Set Name" HeaderStyle-HorizontalAlign="Center" ItemStyle-VerticalAlign="Top" HeaderStyle-Width="15%"/>
                    <telerik:GridBoundColumn UniqueName="VeeamBackupTypeName" DataField="VeeamBackupTypeName" SortExpression="VeeamBackupTypeName" HeaderText="Veeam Job Type" HeaderTooltip="Veeam Job Type" HeaderStyle-HorizontalAlign="Center" ItemStyle-VerticalAlign="Top" HeaderStyle-Width="15%"/>
                    <telerik:GridBoundColumn UniqueName="BackupMonitorStatusName" DataField="BackupMonitorStatusName"  SortExpression="BackupMonitorStatusName" HeaderText="Status" HeaderStyle-HorizontalAlign="Center" ItemStyle-VerticalAlign="Top" HeaderStyle-Width="5%"/>
                    <telerik:GridBoundColumn UniqueName="AppassureReportStartDateTime" DataField="AppassureReportStartDateTime" SortExpression="AppassureReportStartDateTime" HeaderText="BU Date" HeaderTooltip="Backed Up Date" HeaderStyle-HorizontalAlign="Center" ItemStyle-VerticalAlign="Top" HeaderStyle-Width="8%"/>
                    <telerik:GridBoundColumn UniqueName="FullName" DataField="FullName" SortExpression="FullName" HeaderText="Updated By" HeaderTooltip="Updated By" HeaderStyle-HorizontalAlign="Center" ItemStyle-VerticalAlign="Top" HeaderStyle-Width="8%"/>
                    <telerik:GridButtonColumn UniqueName="Delete" CommandName="Delete" Text="Delete" ConfirmText="Confirm Delete" ItemStyle-ForeColor="#DB2929" HeaderStyle-Width="4%" />
                </Columns>
        
            </MasterTableView>
    
        </telerik:RadGrid>
        
    </div>
