<%@ Control Language="C#" AutoEventWireup="true" CodeFile="ClientBackupSetResponsive.ascx.cs" Inherits="UserControl_Grid_ClientBackupSetResponsive" %>
 <div class="table-responsive">
     <telerik:RadGrid ID="rgClientBackupSet" runat="server"
        OnNeedDataSource="rgClientBackupSet_NeedDataSource" 
        OnItemDataBound="rgClientBackupSet_ItemDataBound" 
        OnPreRender="rgClientBackupSet_PreRender"
        OnUpdateCommand="rgClientBackupSet_UpdateCommand"
        OnInsertCommand="rgClientBackupSet_InsertCommand" 
        OnItemCommand="rgClientBackupSet_ItemCommand" 
        OnItemCreated="rgClientBackupSet_ItemCreated"
       
        Skin="3b" EnableEmbeddedSkins="false"
        AllowSorting="true" AllowPaging="true" AllowCustomPaging="true" AutoGenerateColumns="false"
        AutoGenerateDeleteColumn="false" AutoGenerateEditColumn="false" ShowFooter="false" Width="100%" GridLines="None" ClientSettings-Resizing-AllowColumnResize="true">
    
            
        <ClientSettings EnableRowHoverStyle="true" AllowColumnsReorder="true" >
            <Selecting AllowRowSelect="true" />
            <Resizing AllowColumnResize="true" ClipCellContentOnResize="false" />
        </ClientSettings>
    
        <MasterTableView ShowHeadersWhenNoRecords="true" TableLayout="Fixed" InsertItemPageIndexAction="ShowItemOnCurrentPage"
            DataKeyNames="Id,Active" CommandItemDisplay="Top" EditMode="EditForms" Width="100%" >
            <PagerStyle AlwaysVisible="true" Mode="NextPrevAndNumeric" PageSizes="10,25,50,100,250" PageSizeControlType="RadComboBox" Position="Bottom" />
            <NoRecordsTemplate>
                <div style="padding: 8px 0 8px 5px;">No Records found.</div>
            </NoRecordsTemplate>
            <EditFormSettings UserControlName="/UserControl/Grid/EditForm/BackupSetEditResponsive.ascx" EditFormType="WebUserControl">
                <EditColumn UniqueName="EditCommandColumn1"></EditColumn>
            </EditFormSettings>
           <CommandItemTemplate>
               <div style="margin:5px 5px;">
                   <asp:LinkButton ID="btnAdd" runat="server" CommandName="InitInsert" style="padding-right:10px;"><i class="gi gi-circle_plus" title="Add"></i> Add Backup task</asp:LinkButton>
                   <asp:LinkButton ID="btnRefresh" runat="server" CommandName="RebindGrid" CssClass="pull-right"><i class="gi gi-refresh" title="Refresh"></i>  Refresh</asp:LinkButton>
               </div>
           </CommandItemTemplate>            
            <Columns>
                <telerik:GridEditCommandColumn UniqueName="Edit" HeaderStyle-Width="4%" EditText="Edit" />
                <telerik:GridBoundColumn UniqueName="Company" DataField="Company" SortExpression="Company" HeaderText="Client" HeaderStyle-HorizontalAlign="Center" HeaderStyle-Width="15%" ItemStyle-VerticalAlign="Top" />
                <telerik:GridBoundColumn UniqueName="Server" DataField="Server" SortExpression="Server" HeaderText="Server Name" HeaderStyle-HorizontalAlign="Center" HeaderStyle-Width="10%" ItemStyle-VerticalAlign="Top" />
                <telerik:GridBoundColumn UniqueName="SupportingTableDescription" DataField="SupportingTableDescription" SortExpression="SupportingTableDescription" HeaderText="Backup Type" HeaderStyle-HorizontalAlign="Center" HeaderStyle-Width="8%" ItemStyle-VerticalAlign="Top" />
                <telerik:GridBoundColumn UniqueName="Name" DataField="Name" SortExpression="Name" HeaderText="Backup Set Name" HeaderStyle-HorizontalAlign="Center" HeaderStyle-Width="12%" ItemStyle-VerticalAlign="Top" />
                <telerik:GridBoundColumn UniqueName="Description" DataField="Description" SortExpression="Description" HeaderText="Backup Set Description" HeaderStyle-HorizontalAlign="Center" HeaderStyle-Width="18%" ItemStyle-VerticalAlign="Top" /> 
                <telerik:GridBoundColumn UniqueName="BackupServer" DataField="BackupServer" SortExpression="BackupServer" HeaderText="Backup Server" HeaderStyle-HorizontalAlign="Center" HeaderStyle-Width="10%" ItemStyle-VerticalAlign="Top" /> 
                <telerik:GridBoundColumn UniqueName="Created" DataField="Created" SortExpression="Created" HeaderText="Created" HeaderStyle-HorizontalAlign="Center" HeaderStyle-Width="7%" ItemStyle-VerticalAlign="Top" /> 
                <telerik:GridBoundColumn UniqueName="Active" DataField="Active" SortExpression="Active" HeaderText="Active" HeaderStyle-HorizontalAlign="Center" HeaderStyle-Width="5%" ItemStyle-VerticalAlign="Top" />
                <telerik:GridButtonColumn UniqueName="Deactivate" HeaderStyle-Width="7%" />
                <telerik:GridButtonColumn UniqueName="Delete" CommandName="Delete" Text="Delete" ConfirmText="Confirm Delete" ItemStyle-ForeColor="#DB2929" HeaderStyle-Width="5%" />
            </Columns>
        
        </MasterTableView>
    
    </telerik:RadGrid>
 </div>