<%@ Control Language="C#" AutoEventWireup="true" CodeFile="ClientPatchReportUser.ascx.cs" Inherits="UserControl_Grid_ClientPatchReportUser" %>
<asp:Literal ID="litMessage" runat="server" />
<div class="table-responsive">
    <telerik:RadGrid ID="rgPatchReportUser" runat="server" Skin="3b" EnableEmbeddedSkins="false" Visible="false"
        OnNeedDataSource="rgPatchReportUser_NeedDataSource" 
        OnItemDataBound="rgPatchReportUser_ItemDataBound"
        OnPreRender="rgPatchReportUser_PreRender" 
        OnItemCommand="rgPatchReportUser_ItemCommand"
        AllowSorting="true" AllowPaging="true" AllowCustomPaging="true" AutoGenerateColumns="false" AllowMultiRowSelection="true"
        AutoGenerateDeleteColumn="false" AutoGenerateEditColumn="false" ShowFooter="false" Width="100%" GridLines="None">
        <MasterTableView ShowHeadersWhenNoRecords="true" TableLayout="Fixed" Width="100%" CommandItemDisplay="None" DataKeyNames="Id">
            <NoRecordsTemplate>
                <div style="padding: 8px 0 8px 5px;">No Records found.</div>
            </NoRecordsTemplate>
            <Columns>
                <telerik:GridTemplateColumn UniqueName="Id" HeaderText="" HeaderStyle-Width="20%">
                    <ItemTemplate>
                        <asp:LinkButton ID="btnRemove" runat="server" CausesValidation="false" CommandName="Remove" style="padding-left:10px;" OnClientClick="javascript:return confirm('Remove?');"><i class="gi gi-circle_remove" title="Remove"></i></asp:LinkButton>
                    </ItemTemplate> 
                </telerik:GridTemplateColumn> 
                <telerik:GridBoundColumn UniqueName="FullName" DataField="FullName" SortExpression="FullName" HeaderText="Name" HeaderStyle-HorizontalAlign="Center" HeaderStyle-Width="80%" />
            </Columns>
        </MasterTableView>
    </telerik:RadGrid>
</div>