<%@ Control Language="C#" AutoEventWireup="true" CodeFile="TicketDashboardResponsive.ascx.cs" Inherits="UserControl_Grid_TicketDashboardResponsive" %>
<%@ Register TagPrefix="uc" TagName="TicketRecurring" Src="~/UserControl/DropDownList/TicketRecurring.ascx" %>
<%@ Register TagPrefix="ddl" TagName="TicketView" Src="~/UserControl/DropDownList/TicketView.ascx" %>
<%@ Register TagPrefix="ddl" TagName="UserTicketTag" Src="~/UserControl/DropDownList/UserTicketTags.ascx" %>
<%@ Register TagPrefix="ddl" TagName="GridExportType" Src="~/UserControl/DropDownList/GridExportType.ascx" %>

<telerik:radscriptblock id="RadScriptBlock1" runat="server">
    <script type="text/javascript">
        //On insert and update buttons click temporarily disables ajax to perform upload actions
        //also disable ajax for export button click
        function conditionalPostback(e, sender) {
            var theRegexp = new RegExp("\.btnUpdate$|\.btnAdd$|\.InitInsertButton$|\.lbMakeActive$", "ig"); 
            var theRegexp2 = new RegExp("\.btnExport$", "ig");
            
            if ((sender.EventTarget.match(theRegexp) && sender.get_eventTarget().indexOf("rgTicketFile") > -1) || (sender.EventTarget.match(theRegexp2)))
            {
                sender.EnableAjax = false;
            }
        }
    </script>
</telerik:radscriptblock>

<telerik:RadNotification ID="rnConfirmation" runat="server" Width="250" Height="100" EnableRoundedCorners="true" VisibleTitlebar="false" Pinned="false" Position="Center" Skin="Black" AnimationDuration="150" Animation="FlyIn"/>

<div class="block">
    <ajaxToolkit:CollapsiblePanelExtender ID="cpeTicket" 
        runat="Server"
        TargetControlID="pnlContainer"
        ExpandControlID="pnlShowHideTicket"
        CollapseControlID="pnlShowHideTicket" 
        Collapsed="False"
        BehaviorID="cpeBehaviorTicket"
        TextLabelID="lblTicketHeader"
        ImageControlID="imgTicketHeader"    
        ExpandedImage="~/images/collapse_blue.jpg"
        CollapsedImage="~/Images/expand_blue.jpg"
        SuppressPostBack="true" />
    <div class="block-title">
        <asp:Panel ID="pnlShowHideTicket" runat="server" CssClass="collapsePanelHeaderTicket" Height="25px">
            <div style="cursor: pointer; vertical-align: middle; padding:5px;">
                <div style="float: left;">
                    <asp:Label ID="lblTicketHeader" Font-Bold="true" runat="server" />
                </div>
                <div style="float: right; vertical-align: middle;">
                    <asp:ImageButton ID="imgTicketHeader" runat="server" ImageUrl="~/images/expand_blue.jpg" />
                </div>
            </div>
        </asp:Panel>
    </div>
    <asp:Panel ID="pnlContainer" runat="server">
        <asp:Panel ID="pnlHeader" runat="server">
            <asp:Table ID="tblGridHeader" runat="server" CellPadding="0" CellSpacing="0" CssClass="GridHeaderTable">
                <asp:TableRow>
                    <asp:TableHeaderCell ID="tblGridHeaderCell1" runat="server" Width="20%">
                        <asp:Literal ID="litLastUpdated" runat="server" />
                    </asp:TableHeaderCell>
                    <asp:TableCell ID="tblGridHeaderCell3" runat="server" Width="16%" Visible="false">
                        Views:&nbsp;
                        <ddl:TicketView ID="ucTicketView" runat="server" ViewType="HomePage" DisplayDefaultValue="false" IsRequired="false" Width="150" Visible="false" HighlightUserViews="true"/>
                    </asp:TableCell>
                    <asp:TableCell ID="tblGridHeaderCell4" runat="server" Width="20%">
                        Tags:&nbsp;
                        <ddl:UserTicketTag ID="ucUserTicketTags" runat="server" DisplayDefaultValue="true" DefaultText="" DefaultValue="" IsRequired="false" Width="150"/>
                    </asp:TableCell>
                </asp:TableRow>
            </asp:Table>
        </asp:Panel>
    
        <asp:PlaceHolder ID="phEditors" runat="server" />
        <asp:Literal ID="litDebug" runat="server" />
        <div class="table-responsive">
            <telerik:RadGrid ID="rgTicket" runat="server" Skin="BitByBit" EnableEmbeddedSkins="false"
                OnNeedDataSource="rgTicket_NeedDataSource" OnItemDataBound="rgTicket_ItemDataBound"
                OnPreRender="rgTicket_PreRender"
                OnItemCreated="rgTicket_ItemCreated"
                OnUpdateCommand="rgTicket_UpdateCommand"
                OnInsertCommand="rgTicket_InsertCommand"
                OnItemCommand="rgTicket_ItemCommand"
                OnRowDrop="rgTicket_RowDrop"
                OnSortCommand="rgTicket_SortCommand" HeaderStyle-Font-Bold="true"
                AllowSorting="true" AllowPaging="true" AllowCustomPaging="true" AutoGenerateColumns="false" AllowMultiRowSelection="true" AllowMultiRowEdit="true"
                AutoGenerateDeleteColumn="false" AutoGenerateEditColumn="false" ShowFooter="false" Width="100%" GridLines="None" ClientSettings-Resizing-AllowColumnResize="true"> 
                <ClientSettings EnableRowHoverStyle="true" AllowColumnsReorder="true">
                    <Selecting AllowRowSelect="true" />
                    <Resizing AllowColumnResize="true" ClipCellContentOnResize="false" />
                    <ClientMessages DragToGroupOrReorder="" DragToResize="" DropHereToReorder="" />    
                </ClientSettings>
                <SortingSettings SortToolTip="" />
                <MasterTableView ShowHeadersWhenNoRecords="true" TableLayout="Fixed" InsertItemPageIndexAction="ShowItemOnCurrentPage"
                    DataKeyNames="Id,TaggedTicketId,AwaitingResponseUserId,Priority,CompanyName,UseHelpDesk,UserClientId,UserFirstName,AssignedTo,FkDisposition,AssignedToUserEmail,IsRecurring,UserLastName,FkClient,AwaitingResponseInternal" 
                    CommandItemDisplay="Top" EditMode="EditForms" Width="100%" CommandItemSettings-AddNewRecordText="Add Ticket" 
                    PagerStyle-ShowPagerText="true" >

                    <PagerStyle AlwaysVisible="true" Mode="NextPrevAndNumeric" PageSizes="10,25,50,100,250" PageSizeControlType="RadComboBox" Position="Bottom" />
                    <NoRecordsTemplate>
                        <div style="padding: 8px 0 8px 5px;">No Records found.</div>
                    </NoRecordsTemplate>
                    <CommandItemTemplate>
                        <table class="rgCommandRow" style="width:100%">
                            <asp:MultiView ID="mvCommandTemplate" runat="server" ActiveViewIndex="0">
                                <asp:View ID="viewCommandTemplateDefault" runat="server">
                                        <tr>    
                                        <td style="width:13%">
                                            <asp:LinkButton ID="lbAddTicket" runat="server" CommandName="AddNewTicket">
                                                <img style="border:0px; padding-right:5px;" alt="" src="/RadControls/Skin/Grid/BitByBit/AddRecord.gif"/>Add Ticket
                                            </asp:LinkButton>
                                        </td>
                                        <td style="width:15%; vertical-align:central">
                                            <asp:LinkButton ID="lbCloseTickets" runat="server" CommandName="CloseSelected"
                                                OnClientClick="javascript:return confirm('Close all selected tickets?')">
                                                    <img style="border:0px; padding-right:5px;" alt="" src="/RadControls/Skin/Grid/BitByBit/Cancel.gif" />Close Selected Tickets
                                            </asp:LinkButton>
                                        </td>
                                        <td style="width:10%" align="center">
                                            <asp:LinkButton ID="lbEditAll" runat="server" CommandName="EditAll">
                                                    <img style="border:0px; padding-right:5px;" alt="" src="/RadControls/Skin/Grid/BitByBit/Edit.gif" />Edit All
                                            </asp:LinkButton>   
                                        </td>
                                        <td style="width:15%" align="center">
                                            <asp:LinkButton ID="lbTicketMerge" runat="server" CommandName="TicketMerge">
                                                    <img style="border:0px; padding-right:5px;" alt="" src="/RadControls/Skin/Grid/BitByBit/Update.gif" />Merge Selected Tickets
                                            </asp:LinkButton>   
                                        </td>
                                        <td style="width:15%" align="center">
                                            <ddl:GridExportType ID="ucGridExportType" runat="server" />&nbsp;
                                            <asp:LinkButton ID="btnExport" runat="server" Text="Export" OnClick="btnExport_Click"/>
                                        </td>
                                        <td style="width:15%" align="right">
                                            <asp:LinkButton ID="lbRefresh" runat="server" CommandName="RefreshGrid">
                                                <img style="border:0px; padding-right:5px;" alt="" src="/RadControls/Skin/Grid/BitByBit/Refresh.gif" />Refresh
                                            </asp:LinkButton>
                                        </td>
                                    </tr>
                                </asp:View>

                                <asp:View ID="viewCommandTemplateBatchEdit" runat="server">
                                    <tr>
                                        <td style="width:45%" align="right">
                                            <asp:LinkButton ID="lbUpdateAll" runat="server" CommandName="UpdateAll" ValidationGroup="vgTicketBatchEdit" CausesValidation="true">
                                                <img style="border:0px; padding-right:5px;" alt="" src="/RadControls/Skin/Grid/BitByBit/Update.gif" />Update All
                                            </asp:LinkButton>
                                        </td>
                                        <td style="width:10%" align="left"></td>
                                        <td style="width:45%" align="left">
                                            <asp:LinkButton ID="lbCancelUpdateAll" runat="server" CommandName="CancelUpdateAll">
                                                <img style="border:0px; padding-right:5px;" alt="" src="/RadControls/Skin/Grid/BitByBit/Cancel.gif" />Cancel
                                            </asp:LinkButton>
                                        </td>
                                    </tr>
                                </asp:View>

                        
                            </asp:MultiView>
                        </table>
                    </CommandItemTemplate> 
        
                    <EditFormSettings UserControlName="/UserControl/Grid/EditForm/TicketEdit.ascx" EditFormType="WebUserControl">
                        <EditColumn UniqueName="EditCommandColumn"></EditColumn>
                    </EditFormSettings>
                    <Columns>
                        <telerik:GridTemplateColumn UniqueName="CheckBoxTemplateColumn" HeaderStyle-Width="3%" ItemStyle-HorizontalAlign="Center">
                            <ItemTemplate>
                                <asp:CheckBox ID="cbCheck" runat="server" />
                            </ItemTemplate>
                        </telerik:GridTemplateColumn>
                        <telerik:GridTemplateColumn DataField="Id" ItemStyle-HorizontalAlign="Left" HeaderStyle-Width="5%" HeaderText="" UniqueName="ActionColumn">
                            <ItemTemplate>
                                <asp:LinkButton ID="btnMakeActive" runat="server" ToolTip="Make Active" OnClientClick="javascript:return confirm('Make Active?');">
                                    <i class="gi gi-circle_arrow_right" title="Make Active"></i></asp:LinkButton>
                            </ItemTemplate>
                        </telerik:GridTemplateColumn>
                        <telerik:GridBoundColumn DataField="PriorityName" HeaderStyle-Width="3%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="P#" SortExpression="PriorityName" UniqueName="PriorityName" HeaderTooltip="Ticket Priority" />
                        <telerik:GridBoundColumn DataField="Id" Display="false" HeaderStyle-Width="13%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="No." SortExpression="Id" UniqueName="Id" HeaderTooltip="TNo." />
                        <telerik:GridTemplateColumn DataField="Id" ItemStyle-HorizontalAlign="Left" HeaderStyle-Width="8%" HeaderText="No." UniqueName="Id" SortExpression="Id" HeaderTooltip="TNo.">
                            <ItemTemplate>
                                <asp:Label ID="lblTicketNo" runat="server" Text='<%# Eval("Id") %>' />
                                <asp:LinkButton ID="btnClearAwaitingResponse" runat="server" ToolTip="Clear Awaiting Reponse Flag" CommandName="ClearClearAwaitingResponse" OnClientClick="javascript:return confirm('Clear Flag?');" style="padding-left:5px;" >
                                    <i class="gi gi-circle_minus" title="Clear Awaiting Reponse Flag"></i></asp:LinkButton>
                            </ItemTemplate>
                        </telerik:GridTemplateColumn>
                        <telerik:GridTemplateColumn DataField="Summary" ItemStyle-HorizontalAlign="Left" HeaderStyle-Width="20%" HeaderText="Summary" UniqueName="Summary" HeaderTooltip="Summary">
                            <ItemTemplate>
                                <asp:HyperLink ID="btnEditRecord" runat="server" Text='<%# Eval("Summary") %>' NavigateUrl='<%# Eval("Id","/Ticket/Detail2.aspx?Id={0}") %>' />
                            </ItemTemplate>
                        </telerik:GridTemplateColumn>
                        <telerik:GridBoundColumn DataField="CompanyName" HeaderStyle-Width="20%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Company" SortExpression="CompanyName" UniqueName="CompanyName" HeaderTooltip="Company Name"/>
                        <telerik:GridBoundColumn DataField="DispositionName" HeaderStyle-Width="8%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Status" SortExpression="DispositionName" UniqueName="DispositionName" HeaderTooltip="Disposition Name"/>
                        <telerik:GridBoundColumn DataField="TicketTypeName" HeaderStyle-Width="7%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Type" SortExpression="TicketTypeName" UniqueName="TicketTypeName" HeaderTooltip="Ticket Type" />
                        <telerik:GridBoundColumn DataField="DateEntered" HeaderStyle-Width="15%" DataType="System.DateTime" ItemStyle-HorizontalAlign="Left" HeaderText="Entered" SortExpression="DateEntered" UniqueName="DateEntered" HeaderTooltip="Date Entered" DataFormatString="{0:MM/dd/yy HH:mm}" />
                        <telerik:GridBoundColumn DataField="LastUpdated" HeaderStyle-Width="15%" DataType="System.DateTime" ItemStyle-HorizontalAlign="Left" HeaderText="Updated" SortExpression="LastUpdated" UniqueName="LastUpdated" HeaderTooltip="Date Last Updated" DataFormatString="{0:MM/dd/yy HH:mm}" />
                        <telerik:GridBoundColumn DataField="UserFirstName" HeaderStyle-Width="7%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Assigned" SortExpression="UserFirstName" UniqueName="UserFirstName" HeaderTooltip="Assigned To" />
                        <telerik:GridBoundColumn DataField="HoursToFix" HeaderStyle-Width="7%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Est." SortExpression="HoursToFix" UniqueName="HoursToFix" HeaderTooltip="Estimate" />
                        <telerik:GridBoundColumn DataField="TaggedTicketId" HeaderStyle-Width="3%" Display="false" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Tag" SortExpression="TaggedTicketId" UniqueName="Tag1" HeaderTooltip="Tag" />
                        <telerik:GridTemplateColumn DataField="TaggedTicketId" ItemStyle-HorizontalAlign="Left" HeaderStyle-Width="3%" HeaderText="Tag" UniqueName="Tag">
                            <ItemTemplate>
                                <asp:LinkButton ID="lbTagged" runat="server" Text='<%# Eval("TaggedTicketId") %>' ToolTip="Tag"></i></asp:LinkButton>
                            </ItemTemplate>
                        </telerik:GridTemplateColumn>
                        <telerik:GridBoundColumn DataField="Description" HeaderStyle-Width="17%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Description" SortExpression="Description" UniqueName="Description" HeaderTooltip="Description" />
                        <telerik:GridBoundColumn DataField="ScheduledDate" Display="false" HeaderStyle-Width="17%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Scheduled" SortExpression="ScheduledDate" UniqueName="ScheduledDate" HeaderTooltip="ScheduledDate" DataFormatString="{0:MM/dd/yy HH:mm}" />
                    </Columns>
                </MasterTableView>
            </telerik:RadGrid>
        </div>

        <telerik:RadWindowManager ID="rwmTicketMerge" runat="server" EnableShadow="true" />
    </asp:Panel>
</div>

