<%@ Control Language="C#" AutoEventWireup="true" CodeFile="TicketTagResponsive.ascx.cs" Inherits="UserControl_Grid_TicketTagResponsive" %>
<asp:Literal ID="litMessage" runat="server" />
<div class="table-responsive">
    <telerik:RadGrid ID="rgTicketTag" runat="server" Skin="3b" EnableEmbeddedSkins="false" Visible="false"
        OnNeedDataSource="rgTicketTag_NeedDataSource" 
        OnItemDataBound="rgTicketTag_ItemDataBound"
        OnPreRender="rgTicketTag_PreRender" 
        OnItemCommand="rgTicketTag_ItemCommand"
        AllowSorting="true" AllowPaging="true" AllowCustomPaging="true" AutoGenerateColumns="false" AllowMultiRowSelection="false"
        AutoGenerateDeleteColumn="false" AutoGenerateEditColumn="false" ShowFooter="false" Width="100%" GridLines="None">
        <MasterTableView ShowHeadersWhenNoRecords="true" TableLayout="Fixed" Width="100%" CommandItemDisplay="None" DataKeyNames="TaggedTicketValueId,Id">
            <NoRecordsTemplate>
                <div style="padding: 8px 0 8px 5px;">No Records found.</div>
            </NoRecordsTemplate>
            <Columns>
                 <telerik:GridTemplateColumn DataField="Id" ItemStyle-HorizontalAlign="Left" HeaderStyle-Width="10%" HeaderText="" UniqueName="ActionColumn">
                        <ItemTemplate>
                            <asp:LinkButton ID="btnDelete" runat="server" ToolTip="Delete" CommandName="Delete" OnClientClick="javascript:return confirm('Delete?');"> <i class="gi gi-circle_minus" title="Delete"></i></asp:LinkButton>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>
                <telerik:GridBoundColumn UniqueName="Name" DataField="Name" SortExpression="Name" HeaderText="Tag" HeaderStyle-HorizontalAlign="Center" HeaderStyle-Width="65%" />
                <telerik:GridBoundColumn UniqueName="Created" DataField="TaggedTicketValueCreated" SortExpression="TaggedTicketValueCreated" HeaderText="Date" DataFormatString="{0:MM/dd/yy HH:mm}" HeaderStyle-HorizontalAlign="Center" HeaderStyle-Width="25%" />
            </Columns>
        </MasterTableView>
    </telerik:RadGrid>
</div>