<%@ Control Language="C#" AutoEventWireup="true" CodeFile="TicketResponsive.ascx.cs" Inherits="UserControl_Grid_TicketResponsive" %>
<telerik:RadCodeBlock ID="RadCodeBlock1" runat="server">
    <script>
        function CloseMergeTicket() {
            $('#modal-ticket-merge').modal('hide');
            $('body').removeClass('modal-open');
            $('.modal-backdrop').remove();
        }
    </script>
</telerik:RadCodeBlock>
<!--prod not updated-->
<style>

    .RadGrid_3b .rgRow td,.RadGrid_3b .rgAltRow td,.RadGrid_3b .rgEditRow td,.RadGrid_3b .rgFooter td,.RadGrid_3b .rgFilterRow td,.RadGrid_3b .rgResizeCol,.RadGrid_3b .rgGroupHeader td
    {
	    padding:4px 5px !important;
	    white-space: nowrap;
        overflow:hidden;
    }
    .RadGrid td.rgPagerCell { padding: 10px; }
    .RadGrid_3b .rgPagerCell .rgPagerLabel { padding: 7px 0 7px;}
    .RadDropDownList .rddlInner {height:25px; margin-top:6px;}
    .RadGrid_3b .RadComboBox .rcbInput {width:50px !important;}
    /*selected*/
    .RadGrid_3b .rgMasterTable .rgSelectedCell,
    .RadGrid_3b .rgSelectedRow > td,
    .RadGrid_3b td.rgEditRow .rgSelectedRow,
    .RadGrid_3b .rgSelectedRow td.rgSorted {
        color: #ffffff;
        background: #07313a;
        border-color: #ffffff;}
    .RadGrid_3b .rgSelectedRow.rgHoveredRow {
        background: #07313a; }
    .RadGrid_3b .rgSelectedCell a,
    .RadGrid_3b .rgSelectedRow a {
        color: #ffffff; }
</style>
<asp:PlaceHolder ID="phTabletPagerCss" runat="server" Visible="false">
    <style>
        .RadGrid_3b .rgPagerCell .rgNumPart span { width:25px; }
        .RadGrid_3b .rgPagerCell .rgPagePrev, .rgPageFirst, .rgPageNext, .rgPageLast {display:none; } 
    </style>
</asp:PlaceHolder>
 <div class="table-responsive">
    <telerik:RadGrid ID="rgTicket" runat="server" Skin="3b" EnableEmbeddedSkins="false"
        OnNeedDataSource="rgTicket_NeedDataSource" 
        OnPreRender="rgTicket_PreRender" 
        OnItemDataBound="rgTicket_ItemDataBound" 
        OnSortCommand="rgTicket_SortCommand"
        OnItemCommand="rgTicket_ItemCommand"  
        OnItemCreated="rgTicket_ItemCreated"
        OnPageSizeChanged="rgTicket_PageSizeChanged"
        AllowSorting="true" AllowPaging="true" AllowCustomPaging="true" AutoGenerateColumns="false"
        AutoGenerateDeleteColumn="false" AutoGenerateEditColumn="false" ShowFooter="false" Width="100%" GridLines="None" ClientSettings-Resizing-AllowColumnResize="true"> 
        <MasterTableView ShowHeadersWhenNoRecords="true" TableLayout="Fixed" DataKeyNames="Id,AssignedToUserId" Width="100%" CommandItemDisplay="Top">
            <PagerStyle AlwaysVisible="true" Mode="NextPrevAndNumeric" PageSizes="10,25,50,100,250" PageSizeControlType="RadComboBox" Position="Bottom" />
            <NoRecordsTemplate>
                <div style="padding: 8px 0 8px 5px;">No Records found.</div>
            </NoRecordsTemplate>
            <CommandItemTemplate>
                <div style="margin:5px 5px;">
                    <asp:LinkButton ID="btnExport" runat="server" OnClick="btnExport_Click" Visible="true" style="padding-right:10px;"><i class="fi fi-csv" title="Export To CSV"></i>  Export To CSV</asp:LinkButton>
                    <asp:HyperLink ID="btnAdd" runat="server" NavigateUrl="/Ticket/Add2.aspx" style="padding-right:10px;"><i class="gi gi-circle_plus" title="Add Ticket"></i> Add Ticket</asp:HyperLink>
                    <asp:LinkButton ID="btnMerge" runat="server" CommandName="TicketMerge" Visible="false"><i class="gi gi-git_merge" title="Merge Selected Tickets"></i>  Merge Selected Tickets</asp:LinkButton>
                    <asp:LinkButton ID="btnClosed" runat="server" CommandName="Closed" ><i class="gi gi-circle_minus" title="Closed Tickets"></i>  Close Tickets</asp:LinkButton>
                    <asp:LinkButton ID="btnRefresh" runat="server" CommandName="RebindGrid" CssClass="pull-right"><i class="gi gi-refresh" title="Refresh"></i>  Refresh</asp:LinkButton>
                </div>
            </CommandItemTemplate>
            <Columns>
                <telerik:GridTemplateColumn DataField="Id" ItemStyle-HorizontalAlign="Left" HeaderStyle-Width="2%" HeaderText="" UniqueName="ActionColumn">
                    <ItemTemplate>
                        <asp:LinkButton ID="btnMakeActive" runat="server" ToolTip="Make Active" CommandName="MakeActive" Visible="false" OnClientClick="javascript:return confirm('Make Active?');">
                            <i class="gi gi-circle_arrow_right" title="Make Active"></i></asp:LinkButton>
                    </ItemTemplate>
                </telerik:GridTemplateColumn>
                <telerik:GridBoundColumn DataField="Id" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="#" UniqueName="ExportId" Visible="false" />
                <telerik:GridTemplateColumn DataField="Id" ItemStyle-HorizontalAlign="Left" HeaderStyle-Width="7%" HeaderText="#" UniqueName="Id" SortExpression="Id" HeaderTooltip="Ticket Id">
                    <ItemTemplate>
                        <asp:Label ID="lblTicketId" runat="server" />
                        <asp:LinkButton ID="btnClearAwaitingResponse" runat="server" ToolTip="Clear Awaiting Reponse Flag" CommandName="ClearAwaitingResponse" Visible="false" OnClientClick="javascript:return confirm('Clear Flag?');" style="padding-left:5px;" >
                            <i class="gi gi-circle_minus" title="Clear Awaiting Reponse Flag"></i></asp:LinkButton>
                    </ItemTemplate>
                </telerik:GridTemplateColumn>
                <telerik:GridBoundColumn DataField="PriorityName" HeaderStyle-Width="3%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="P#" SortExpression="PriorityName" UniqueName="PriorityName" HeaderTooltip="Ticket Priority" />
                <telerik:GridBoundColumn DataField="Summary" HeaderStyle-Width="18%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Summary" SortExpression="Summary" UniqueName="Summary" HeaderTooltip="Ticket Summary" />
                <telerik:GridBoundColumn DataField="ClientName" HeaderStyle-Width="8%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Company" SortExpression="ClientName" UniqueName="ClientName" HeaderTooltip="Company Name" />
                <telerik:GridBoundColumn DataField="ClientName" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Company" SortExpression="ClientName" UniqueName="ExportClientName" HeaderTooltip="Company Name" Visible="false"/>
                <telerik:GridBoundColumn DataField="ReportedBy" HeaderStyle-Width="9%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Reported By" SortExpression="ReportedBy" UniqueName="ReportedBy" HeaderTooltip="Added By"/>
                <telerik:GridBoundColumn DataField="VIP" HeaderStyle-Width="5%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="VIP" SortExpression="VIP" UniqueName="VIP" HeaderTooltip="VIP"/>
                <telerik:GridBoundColumn DataField="DispositionName" HeaderStyle-Width="5%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Status" SortExpression="DispositionName" UniqueName="DispositionName" HeaderTooltip="Ticket Status" />
                <telerik:GridBoundColumn DataField="TicketTypeName" HeaderStyle-Width="5%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Type" SortExpression="TicketTypeName" UniqueName="TicketTypeName" HeaderTooltip="Ticket Type" />
                <telerik:GridBoundColumn DataField="DateEntered" HeaderStyle-Width="8%" DataType="System.DateTime" ItemStyle-HorizontalAlign="Left" HeaderText="Entered" SortExpression="DateEntered" UniqueName="DateEntered" HeaderTooltip="Date Entered" DataFormatString="{0:MM/dd/yy HH:mm}" />
                <telerik:GridBoundColumn DataField="LastUpdated" HeaderStyle-Width="8%" DataType="System.DateTime" ItemStyle-HorizontalAlign="Left" HeaderText="Updated" SortExpression="LastUpdated" UniqueName="LastUpdated" HeaderTooltip="Date Last Updated" DataFormatString="{0:MM/dd/yy HH:mm}" />
                <telerik:GridBoundColumn DataField="ScheduledDate" HeaderStyle-Width="8%" DataType="System.DateTime" ItemStyle-HorizontalAlign="Left" HeaderText="Scheduled" SortExpression="ScheduledDate" UniqueName="ScheduledDate" HeaderTooltip="Scheduled Date" DataFormatString="{0:MM/dd/yy HH:mm}" />
                <telerik:GridBoundColumn DataField="AssignedToUserName" HeaderStyle-Width="7%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Assigned" SortExpression="AssignedToUserName" UniqueName="AssignedToUserName" HeaderTooltip="Assigned To" />
                <telerik:GridBoundColumn DataField="AssignedToUserName" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Assigned" SortExpression="AssignedToUserName" UniqueName="ExportAssignedToUserName" HeaderTooltip="Assigned To" Visible="false" />
                <telerik:GridBoundColumn DataField="Description" HeaderStyle-Width="12%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Description" SortExpression="Description" UniqueName="Description" HeaderTooltip="Description" />
                <telerik:GridBoundColumn DataField="TimeSheetHours" HeaderStyle-Width="12%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Total Hours" SortExpression="TimeSheetHours" UniqueName="TimeSheetHours" HeaderTooltip="TimeSheetHours" />
                <telerik:GridBoundColumn DataField="ClientLocationName" HeaderStyle-Width="12%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Location" SortExpression="ClientLocationName" UniqueName="ClientLocationName" HeaderTooltip="ClientLocationName" />
                <telerik:GridBoundColumn DataField="PriorityOrder" Display="false" HeaderStyle-Width="3%" DataType="System.Int16" ItemStyle-HorizontalAlign="Left" HeaderText="O" SortExpression="PriorityOrder" UniqueName="PriorityOrder" HeaderTooltip="PriorityOrder" />
                <telerik:GridBoundColumn DataField="UpdateBy" Display="false" HeaderStyle-Width="3%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Update By" SortExpression="UpdateBy" UniqueName="UpdateBy" HeaderTooltip="UpdateBy" />
                <telerik:GridBoundColumn DataField="LastExternalUpdate" Display="false" HeaderStyle-Width="3%" DataType="System.String" ItemStyle-HorizontalAlign="Left" HeaderText="Last External Update" SortExpression="LastExternalUpdate" UniqueName="LastExternalUpdate" HeaderTooltip="LastExternalUpdate" />
            </Columns>
        </MasterTableView>
    </telerik:RadGrid>
</div>
<div id="modal-ticket-merge" class="modal" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3 class="modal-title">Ticket Merge</h3>
            </div>
            <div class="modal-body">
                <asp:MultiView ID="mvTicketMerge" runat="server" ActiveViewIndex="0">
                    <asp:View ID="viewTicketMergeMain" runat="server">
                        <asp:ValidationSummary ID="vsTicketMerge" runat="server" ValidationGroup="vgTicketMerge" CssClass="validationSummary" />
                        <div class="form-horizontal form-bordered">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Tickets To Merge</label>
                                <div class="col-sm-9">
                                    <p class="form-control-static"><asp:Literal ID="litTicketsToMerge" runat="server" /></p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Master Ticket # <span class="text-danger">*</span></label>
                                <div class="col-sm-9">
                                    <asp:TextBox ID="txtMasterTicketNumber" runat="server" CssClass="form-control" MaxLength="7" PlaceHolder="Enter Ticket # ...." />
                                    <asp:RequiredFieldValidator ID="rfvMasterTicketNumber" runat="server" ControlToValidate="txtMasterTicketNumber" ValidationGroup="vgTicketMerge" ErrorMessage="Merge Master Ticket # is required" Display="None" />
                                    <asp:RegularExpressionValidator runat="server" ID="revMasterTicketNumber" ControlToValidate="txtMasterTicketNumber" ValidationExpression="\d+" ErrorMessage="Invalid Merge Master Ticket #" 
                                        ValidationGroup="vgTicketMerge" Display="None" />
                                    <asp:CustomValidator ID="cvMasterTicketNumber" runat="server" ControlToValidate="txtMasterTicketNumber" ValidationGroup="vgTicketMerge" ErrorMessage="Merge Master Ticket # could not be found" 
                                        Display="None" OnServerValidate="cvMasterTicketNumber_ServerValidate"/>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <asp:LinkButton ID="btnTicketMerge" runat="server" class="btn btn-sm btn-primary" OnClick="btnTicketMerge_Click" CausesValidation="true" ValidationGroup="vgTicketMerge"><i class="hi hi-ok"></i> Save</asp:LinkButton>
                                <button type="button" class="btn btn-sm btn-primary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </asp:View>
                    <asp:View ID="viewTicketMergeError" runat="server">
                        No tickets were selected to merge.
                        <div class="modal-footer">
                            <button type="button" class="btn btn-sm btn-primary" data-dismiss="modal">Close</button>
                        </div>
                    </asp:View>
                </asp:MultiView>
            </div>
        </div>
    </div>
</div>
<asp:Literal ID="litDebug" runat="server" />