<%@ Control Language="C#" AutoEventWireup="true" CodeFile="TicketContact.ascx.cs" Inherits="UserControl_Grid_TicketContactResponsive" %>
<asp:Literal ID="litMessage" runat="server" />
<div class="table-responsive">
    <telerik:RadGrid ID="rgTicketContact" runat="server" Skin="3b" EnableEmbeddedSkins="false" Visible="false"
        OnNeedDataSource="rgTicketContact_NeedDataSource" 
        OnItemDataBound="rgTicketContact_ItemDataBound"
        OnPreRender="rgTicketContact_PreRender" 
        OnItemCommand="rgTicketContact_ItemCommand"
        AllowSorting="true" AllowPaging="true" PageSize="10" AutoGenerateColumns="false" AllowMultiRowSelection="true"
        AutoGenerateDeleteColumn="false" AutoGenerateEditColumn="false" ShowFooter="false" Width="100%" GridLines="None">
        <MasterTableView ShowHeadersWhenNoRecords="true" TableLayout="Fixed" Width="100%" CommandItemDisplay="None" DataKeyNames="Email,Id">
            <PagerStyle AlwaysVisible="true" Mode="NextPrevAndNumeric" />
            <NoRecordsTemplate>
                <div style="padding: 8px 0 8px 5px;">No Records found.</div>
            </NoRecordsTemplate>
            <Columns>
                <telerik:GridTemplateColumn UniqueName="Email" HeaderText="" HeaderStyle-Width="20%">
                    <HeaderTemplate>
                        <span style="font-weight:normal;">Uncheck All</span><asp:CheckBox ID="chkUncheckAll" runat="server" AutoPostBack="true" OnCheckedChanged="chkUncheckAll_CheckedChanged" style="padding-left:10px; margin-top:4px;" />
                    </HeaderTemplate>
                    <ItemTemplate>
                        <asp:CheckBox ID="chkEmail" runat="server" AutoPostBack="true" OnCheckedChanged="chkEmail_CheckedChanged" />
                        <asp:LinkButton ID="btnRemove" runat="server" CausesValidation="false" CommandName="Remove" style="padding-left:10px;" OnClientClick="javascript:return confirm('Remove?');"><i class="gi gi-circle_remove" title="Remove"></i></asp:LinkButton>
                    </ItemTemplate> 
                </telerik:GridTemplateColumn> 
                <telerik:GridBoundColumn UniqueName="FullName" DataField="FullName" SortExpression="FullName" HeaderText="Name" HeaderStyle-HorizontalAlign="Center" HeaderStyle-Width="80%" />
            </Columns>
        </MasterTableView>
    </telerik:RadGrid>
</div>