<%@ Control Language="C#" AutoEventWireup="true" CodeFile="TicketFileResponsive.ascx.cs" Inherits="UserControl_Grid_TicketFileResponsive"%>
<style>
    .RadGrid td.rgPagerCell { padding: 10px; }
    .RadGrid_3b .rgPagerCell .rgPagerLabel { padding: 7px 0 7px;}
    .RadDropDownList .rddlInner {height:25px; margin-top:6px;}
</style>
<asp:PlaceHolder ID="phTabletPagerCss" runat="server" Visible="false">
    <style>
        .RadGrid_3b .rgPagerCell .rgNumPart span { width:25px; }
        .RadGrid_3b .rgPagerCell .rgPagePrev, .rgPageFirst, .rgPageNext, .rgPageLast {display:none; } 
    </style>
</asp:PlaceHolder>
<asp:Literal ID="litMessage" runat="server" />
<div class="table-responsive" id="divTicketFile">
    <telerik:RadGrid ID="rgTicketFile" runat="server" Skin="3b" EnableEmbeddedSkins="false" Visible="false"
        OnNeedDataSource="rgTicketFile_NeedDataSource" 
        OnItemDataBound="rgTicketFile_ItemDataBound"
        OnPreRender="rgTicketFile_PreRender" 
        OnItemCommand="rgTicketFile_ItemCommand"
        AllowSorting="true" AllowPaging="true" AutoGenerateColumns="false" AllowMultiRowSelection="false" PageSize="10"
        AutoGenerateDeleteColumn="false" AutoGenerateEditColumn="false" ShowFooter="false" Width="100%" GridLines="None">
        <MasterTableView ShowHeadersWhenNoRecords="true" TableLayout="Fixed" Width="100%" CommandItemDisplay="None" DataKeyNames="pcscdefectfile">
            <PagerStyle AlwaysVisible="true" Mode="NextPrevAndNumeric" PageSizes="25,50,100,250" PageSizeControlType="RadDropDownList" Position="Bottom"/>
            <NoRecordsTemplate>
                <div style="padding: 8px 0 8px 5px;">No Records found.</div>
            </NoRecordsTemplate>
            <Columns>
                <telerik:GridTemplateColumn DataField="Id" ItemStyle-HorizontalAlign="Left" HeaderStyle-Width="10%" HeaderText="" UniqueName="Action">
                    <ItemTemplate>
                        <asp:LinkButton ID="btnView" runat="server" CommandName="ViewFile" style="padding-right:10px;"><i class="gi gi-search" title="ViewFile"></i></asp:LinkButton>
                        <asp:LinkButton ID="btnDelete" runat="server" CommandName="Delete" OnClientClick="javascript:if(!confirm('Confirm Deletion?')){return false;}">
                            <i class="gi gi-circle_remove" title="Delete Attachment"></i></asp:LinkButton>
                    </ItemTemplate>
                </telerik:GridTemplateColumn> 
                <telerik:GridTemplateColumn UniqueName="EmailFile" HeaderText="Attach" HeaderStyle-Width="10%">
                    <ItemTemplate><asp:CheckBox ID="chkEmailFile" runat="server"/></ItemTemplate> 
                </telerik:GridTemplateColumn> 
                <telerik:GridTemplateColumn DataField="Name" HeaderStyle-Width="40%" HeaderText="File Name" UniqueName="Name" SortExpression="Name" HeaderStyle-HorizontalAlign="Center">
                    <ItemTemplate>
                        <asp:LinkButton ID="btnViewFile" runat="server" CommandName="ViewFile" />
                    </ItemTemplate>
                </telerik:GridTemplateColumn>
                <telerik:GridBoundColumn UniqueName="UploadedBy" DataField="UploadedBy" SortExpression="UserLast" HeaderText="Uploaded By" HeaderStyle-HorizontalAlign="Center" HeaderStyle-Width="20%" />
                <telerik:GridBoundColumn UniqueName="Created" DataField="Created" DataFormatString="{0:MM/dd/yy HH:mm}" SortExpression="Created" HeaderText="Date" HeaderStyle-HorizontalAlign="Center" HeaderStyle-Width="20%" />
            </Columns>
        </MasterTableView>
    </telerik:RadGrid>
</div>