<%@ Control Language="C#" AutoEventWireup="true" CodeFile="TicketHistoryResponsive.ascx.cs" Inherits="UserControl_Grid_TicketHistoryResponsive" %>
<style>
    .RadGrid td.rgPagerCell { padding: 10px; }
    .RadGrid_3b .rgPagerCell .rgPagerLabel { padding: 7px 0 7px;}
    .RadDropDownList .rddlInner {height:25px; margin-top:6px;}
</style>
<asp:PlaceHolder ID="phTabletPagerCss" runat="server" Visible="false">
    <style>
        .RadGrid_3b .rgPagerCell .rgNumPart span { width:25px; }
        .RadGrid_3b .rgPagerCell .rgPagePrev, .rgPageFirst, .rgPageNext, .rgPageLast {display:none; } 
    </style>
</asp:PlaceHolder>
<div class="table-responsive">
    <telerik:RadGrid ID="rgTicketHistory" runat="server" Skin="3b" EnableEmbeddedSkins="false" Visible="false"
        OnNeedDataSource="rgTicketHistory_NeedDataSource" 
        OnItemDataBound="rgTicketHistory_ItemDataBound"
        OnPreRender="rgTicketHistory_PreRender" 
        OnItemCommand="rgTicketHistory_ItemCommand"
        AllowSorting="true" AllowPaging="true" AllowCustomPaging="true" AutoGenerateColumns="false" AllowMultiRowSelection="false"
        AutoGenerateDeleteColumn="false" AutoGenerateEditColumn="false" ShowFooter="false" PageSize="25" Width="100%" GridLines="None"> 
        <MasterTableView ShowHeadersWhenNoRecords="true" TableLayout="Fixed" Width="100%" CommandItemDisplay="None">
            <PagerStyle AlwaysVisible="true" Mode="NextPrevAndNumeric" PageSizes="25,50,100,250" PageSizeControlType="RadDropDownList" Position="Bottom"/>
            <NoRecordsTemplate>
                <div style="padding: 8px 0 8px 5px;">No Records found.</div>
            </NoRecordsTemplate>
            <CommandItemTemplate>
                <div style="margin:5px 5px;">
                    <asp:LinkButton ID="btnRefresh" runat="server" CommandName="RebindGrid" CssClass="pull-right"><i class="gi gi-refresh" title="Refresh"></i>  Refresh</asp:LinkButton>
                </div>
            </CommandItemTemplate>
            <Columns>
                <telerik:GridBoundColumn UniqueName="Created" DataField="Created" SortExpression="Created" HeaderText="Date" DataFormatString="{0:MM/dd/yy HH:mm}" HeaderStyle-Width="10%" ItemStyle-HorizontalAlign="Left" />
                <telerik:GridBoundColumn UniqueName="Notes" DataField="Notes" SortExpression="Notes" HeaderText="Notes" HeaderStyle-Width="24%" ItemStyle-HorizontalAlign="Left" />
                <telerik:GridBoundColumn UniqueName="UpdatedBy" DataField="UserLast" SortExpression="UserLast" HeaderText="Updated By" HeaderStyle-Width="10%" ItemStyle-HorizontalAlign="Left" />
                <telerik:GridBoundColumn UniqueName="StatusName" DataField="StatusName" SortExpression="StatusName" HeaderText="Status" HeaderStyle-Width="8%" ItemStyle-HorizontalAlign="Left" />
                <telerik:GridBoundColumn UniqueName="EmployeeEmailed" DataField="InternalRecipients" SortExpression="InternalRecipients" HeaderText="Employee Emailed" HeaderStyle-Width="12%" ItemStyle-HorizontalAlign="Left" />
                <telerik:GridBoundColumn UniqueName="ClientEmailed" DataField="ExternalRecipients" SortExpression="ExternalRecipients" HeaderText="Client Emailed" HeaderStyle-Width="12%" ItemStyle-HorizontalAlign="Left" />
                <telerik:GridBoundColumn UniqueName="ViewableBy" DataField="InternalUsage" SortExpression="InternalUsage" HeaderText="Viewable By" HeaderStyle-Width="8%" ItemStyle-HorizontalAlign="Left" />
                <telerik:GridBoundColumn UniqueName="EmailFailure" DataField="EmailFailure" SortExpression="EmailFailure" HeaderText="EF" HeaderTooltip="Email Failure" HeaderStyle-Width="4%" ItemStyle-HorizontalAlign="Left" />
                <telerik:GridBoundColumn UniqueName="Attachments" DataField="Attachments" SortExpression="Attachments" HeaderText="Attachments" HeaderStyle-Width="12%" ItemStyle-HorizontalAlign="Left" />
            </Columns>
        </MasterTableView>
    </telerik:RadGrid>
</div>


