<%@ Control Language="C#" AutoEventWireup="true" CodeFile="TimesheetResponsive.ascx.cs" Inherits="UserControl_Grid_TimesheetResponsive" %>
<style>
    .RadGrid_3b .rgRow td,.RadGrid_3b .rgAltRow td,.RadGrid_3b .rgEditRow td,.RadGrid_3b .rgFooter td,.RadGrid_3b .rgFilterRow td,.RadGrid_3b .rgResizeCol,.RadGrid_3b .rgGroupHeader td
    {
	    padding:4px 5px !important;
	    white-space: nowrap;
        overflow:hidden;
    }
    .RadGrid td.rgPagerCell { padding: 10px; }
    .RadGrid_3b .rgPagerCell .rgPagerLabel { padding: 7px 0 7px;}
    .RadDropDownList .rddlInner {height:25px; margin-top:6px;}
</style>
<asp:PlaceHolder ID="phTabletPagerCss" runat="server" Visible="false">
    <style>
        .RadGrid_3b .rgPagerCell .rgNumPart span { width:25px; }
        .RadGrid_3b .rgPagerCell .rgPagePrev, .rgPageFirst, .rgPageNext, .rgPageLast {display:none; } 
    </style>
</asp:PlaceHolder>
<asp:Literal ID="litMessage" runat="server" Visible="false" />
 <div class="table-responsive">
    <telerik:RadGrid ID="rgTimesheet" runat="server"  Skin="3b" EnableEmbeddedSkins="false"
        OnNeedDataSource="rgTimesheet_NeedDataSource" 
        OnItemDataBound="rgTimesheet_ItemDataBound"
        OnDeleteCommand="rgTimesheet_DeleteCommand"
        OnPreRender="rgTimesheet_PreRender" 
        OnSortCommand="rgTimesheet_SortCommand" 
        AllowSorting="true" AllowPaging="true" AllowCustomPaging="true" AutoGenerateColumns="false" AllowMultiRowSelection="false"
        AutoGenerateDeleteColumn="false" AutoGenerateEditColumn="false" ShowFooter="false" PageSize="50" Width="100%" GridLines="None"> 
       <MasterTableView ShowHeadersWhenNoRecords="true" TableLayout="Fixed" DataKeyNames="Ptimesheet" Width="100%" CommandItemDisplay="Top">
            <PagerStyle AlwaysVisible="true" Mode="NextPrevAndNumeric" PageSizes="25,50,100,250" PageSizeControlType="RadDropDownList" Position="Bottom"/>
            <NoRecordsTemplate>
                <div style="padding: 8px 0 8px 5px;">No Records found.</div>
            </NoRecordsTemplate>
            <CommandItemTemplate>
                <div style="margin:5px 5px;">
                    <asp:LinkButton ID="btnExport" runat="server" OnClick="btnExport_Click" Visible="true"><i class="fi fi-csv" title="Export To CSV"></i>  Export To CSV</asp:LinkButton>
                    <asp:LinkButton ID="btnRefresh" runat="server" CommandName="RebindGrid" CssClass="pull-right"><i class="gi gi-refresh" title="Refresh"></i>  Refresh</asp:LinkButton>
                </div>
            </CommandItemTemplate>
            <Columns>
                <telerik:GridTemplateColumn DataField="pclient" ItemStyle-HorizontalAlign="Left" HeaderStyle-Width="5%" HeaderText="" UniqueName="ActionColumn">
                    <ItemTemplate>
                        <asp:HyperLink ID="btnViewTimesheet" runat="server" NavigateUrl='<%# Eval("Ptimesheet","/Timesheet/Detail2.aspx?TimesheetID={0}") %>' Style="padding-right: 5px;"><i class="gi gi-search" title="View Timesheet"></i></asp:HyperLink>
                        <asp:HyperLink ID="btnViewTicket" runat="server" Style="padding-right: 5px;"><i class="fa fa-ticket" title="View Ticket"></i></asp:HyperLink>
                        <asp:LinkButton ID="btnDeleteTimesheet" runat="server" CommandName="Delete" OnClientClick="if (!confirm('Delete Timesheet?')) {return false;}"><i class="gi gi-circle_remove" title="Delete Timesheet"></i></asp:LinkButton>
                    </ItemTemplate>
                </telerik:GridTemplateColumn>
                <telerik:GridBoundColumn UniqueName="EmployeeCode" DataField="EmployeeCode" SortExpression="EmployeeCode" HeaderText="Employee" HeaderTooltip="Employee Code" HeaderStyle-Width="7%" />
                <telerik:GridBoundColumn UniqueName="Date" DataField="Date" SortExpression="Date" HeaderText="Date" HeaderTooltip="Date" HeaderStyle-Width="7%" />
                <telerik:GridBoundColumn UniqueName="Time" DataField="Time" SortExpression="Time" HeaderText="Start Time" HeaderTooltip="Start Time" HeaderStyle-Width="7%" />
                <telerik:GridBoundColumn UniqueName="Hrs" DataField="Hrs"  SortExpression="Hrs" HeaderText="Hours" HeaderTooltip="Hours" HeaderStyle-Width="5%" />
                <telerik:GridBoundColumn UniqueName="ClientCompany" DataField="ClientCompany" SortExpression="ClientCompany" HeaderText="Client" HeaderTooltip="Client Name" HeaderStyle-Width="15%" />
                <telerik:GridBoundColumn UniqueName="Descr1" DataField="Descr1" SortExpression="Descr1" HeaderText="Activity" HeaderTooltip="Activity" HeaderStyle-Width="11%" />
                <telerik:GridBoundColumn UniqueName="FkCscdefects" DataField="FkCscdefects" SortExpression="FkCscdefects" HeaderText="Ticket #" HeaderTooltip="Ticket # and Summary" HeaderStyle-Width="10%" />
                <telerik:GridBoundColumn UniqueName="Memo" DataField="Memo" SortExpression="Memo" HeaderText="Details" HeaderTooltip="Timesheet Details" HeaderStyle-Width="18%" />
                <telerik:GridBoundColumn UniqueName="ProjectDescr" DataField="ProjectDescr" SortExpression="ProjectDescr" HeaderText="Project" HeaderTooltip="Project" HeaderStyle-Width="14%" />
                <telerik:GridBoundColumn UniqueName="Miles" DataField="Miles" SortExpression="Miles" HeaderText="Mileage" DataType="System.Decimal" HeaderTooltip="Miles" HeaderStyle-Width="7%" />
            </Columns>
        </MasterTableView>
    </telerik:RadGrid>
</div>

<asp:PlaceHolder ID="phGrandTotal" runat="server">
    <br /><p style="font-weight:bold;">Total Hours: <asp:Literal ID="litGrandTotal" runat="server" /></p>
</asp:PlaceHolder>
