using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using DesktopShared.CollectionClasses;
using DesktopShared.EntityClasses;
using DesktopShared.HelperClasses;
using DesktopShared.StoredProcedureCallerClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using Telerik.Web.UI;

public partial class Client_ClientAddProjectTickets : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        GetClientId();
        GetProjectId();

        hlBacktoList.NavigateUrl = String.Format("ClientTicketperProject.aspx?ClientId={0}&ProjectId={1}&TabIndex=6", ClientId, ProjectId);
    }

    #region protected Method
    protected void BindGridAllClientTicket()
    {
        int? _assign = null;

        if (ddlEmployeeAssignedTo.EmployeeId > 0)
            _assign = ddlEmployeeAssignedTo.EmployeeId;

        rgAllTicketClient.DataSource = RetrievalProcedures.ProcGetOpenTicketsforProject(ClientId, "76,58", _assign);
    }
    protected void rgAllTicketClient_NeedDataSource(object sender, Telerik.Web.UI.GridNeedDataSourceEventArgs e)
    {
        BindGridAllClientTicket();
    }
    protected void lbAddTicket_Click(object sender, EventArgs e)
    {
        string _idnumber = string.Empty;
        int _check = 0;
        int rowerror = 0;
        
        foreach (GridDataItem item in rgAllTicketClient.MasterTableView.Items)
        {
            CheckBox cb = item.FindControl("cbBulk") as CheckBox;
            if (cb != null && cb.Checked)
            {
                _check++;
            }
        }
        if (_check == 0)
        {
            DisplayMessage("You need check at least one ticket", Bootstrap.Alert.AlertType.Warning);
            return;
        }

        foreach (GridDataItem item in rgAllTicketClient.MasterTableView.Items)
        {
            CheckBox chkbox = item.FindControl("cbBulk") as CheckBox;
            if (chkbox != null && chkbox.Checked)
            {
                if (DesktopShared.ClientProject.AddTicketProjects(Convert.ToInt32(item["Id"].Text), ProjectId) == false)
                    rowerror++;
            }
        }

        if (rowerror > 0)
            DisplayMessage("Something wrong", Bootstrap.Alert.AlertType.Warning);
        else
        {
            DisplayMessage(String.Format("All Tickets has been {0} - {1}", "Added", DateTime.Now), Bootstrap.Alert.AlertType.Success);
            rgAllTicketClient.Rebind();
        }

    }
    protected void rgAllTicketClient_ItemDataBound(object sender, GridItemEventArgs e)
    {
        if (e.Item is GridDataItem)
        {
            GridDataItem item = e.Item as GridDataItem;
            //foreach (GridColumn col in rgAllTicketClient.MasterTableView.AutoGeneratedColumns)
            //{
            int _cekticketid = DesktopShared.ClientProject.CheckTickeProject(Convert.ToInt32(item["Id"].Text), ProjectId);
            if (_cekticketid > 0)
                item["ActionColumn"].Enabled = false;
            //}
        }
        
    }
    protected void btnSubmit_Click(object sender, EventArgs e)
    {
        BindGridAllClientTicket();
        rgAllTicketClient.Rebind();
    }
    protected void btnClear_Click(object sender, EventArgs e)
    {
        ddlEmployeeAssignedTo.EmployeeId = -1;
    }
    #endregion

    #region Private Method
    /// <summary>
    /// get client id from query string and fetch entity
    /// </summary>
    /// <param name="objClient"></param>
    /// <returns></returns>
    private bool GetClientId()
    {
        int _id = -1;
        if (int.TryParse(BitByBit.Web.Request.GetString("ClientID").Trim(), out _id))
        {
            ClientId = _id;
            return true;
        }

        DesktopShared.Bootstrap.Alert.DisplayMessage(litMessage, String.Format("Unable to fetch client.  ID = {0}", _id > 0 ? _id.ToString() : "N/A"), DesktopShared.Bootstrap.Alert.AlertType.Danger, false);
        pnlMain.Visible = false;
        return false;
    }
    private bool GetProjectId()
    {
        int _id = -1;
        if (int.TryParse(BitByBit.Web.Request.GetString("ProjectId").Trim(), out _id))
        {
            ProjectId = _id;
            return true;
        }

        DesktopShared.Bootstrap.Alert.DisplayMessage(litMessage, String.Format("Unable to fetch client.  ID = {0}", _id > 0 ? _id.ToString() : "N/A"), DesktopShared.Bootstrap.Alert.AlertType.Danger, false);
        pnlMain.Visible = false;
        return false;
    }
    private void DisplayMessage(string message, Bootstrap.Alert.AlertType alertType, bool dismissable = true, string overrideHeader = "")
    {
        ScriptManager.RegisterClientScriptBlock(this, Page.GetType(), "ToTheTop", "ToTopOfPage();", true);
        litMessage.Visible = true;
        litMessage.Text = Bootstrap.Alert.GetDivText(alertType, message, dismissable, true, overrideHeader);
    }

    #endregion

    #region Private properties
    /// <summary>
    /// get/set Project Id
    /// </summary>
    private int ProjectId
    {
        get
        {
            object obj = this.ViewState["proid"];
            return (obj == null) ? 0 : (int)obj;
        }
        set { this.ViewState["proid"] = value; }
    }

    /// <summary>
    /// get/set client id
    /// </summary>
    private int ClientId
    {
        get
        {
            object obj = this.ViewState["scid"];
            return (obj == null) ? 0 : (int)obj;
        }
        set { this.ViewState["scid"] = value; }
    }
    #endregion
    
}